foreground              #FFFFFF
background              #000000
cursor                  #FFFFFF
cursor_text_color       #000000
selection_foreground    #000000
selection_background    #FFFFFF

color0  #000000
color8  #555555
color1  #AAAAAA
color9  #FFFFFF
color2  #AAAAAA
color10 #FFFFFF
color3  #AAAAAA
color11 #FFFFFF
color4  #AAAAAA
color12 #FFFFFF
color5  #AAAAAA
color13 #FFFFFF
color6  #AAAAAA
color14 #FFFFFF
color7  #CCCCCC
color15 #FFFFFF
